### ISSUE TITLE
BugzillaJSONRPCQuery class doesn't exist

### ISSUE THREAD

**Issue by reedy** [mozilla/mediawiki-bugzilla#22]
If you set your $wgBugzillaMethod to json-rpc it tries to use a non existent BugzillaJSONRPCQuery class

FATAL

Fatal error: Class 'BugzillaJSONRPCQuery' not found in /var/www/wiki/mediawiki/core/extensions/mediawiki-bugzilla/BugzillaQuery.class.php on line 13

**Comment by LegNeato** [comment]
Looks like this was added in https://github.com/mozilla/mediawiki-bugzilla/commit/65ee9b8078bbf50e6cfabf692e656386e25798a5
