### ISSUE TITLE
Sometimes throws a divide by zero in php

### ISSUE THREAD

**Issue by superawesome** [mozilla/mediawiki-bugzilla#50]
I only noticed this because of New Relic:

https://rpm.newrelic.com/accounts/263620/applications/2207193/traced_errors/1567128315

https://wiki.mozilla.org/Features/Release_Tracking

I'm guessing it happens when a particular search result returns zero bugs. That page happens to have many uses of this extension, so it's more prone to this than most pages would be.

in unknown called at /data/www/wiki.mozilla.org/wiki/extensions/Bugzilla/templates/bug/table.tpl (69)
…t /data/www/wiki.mozilla.org/wiki/extensions/Bugzilla/
BugzillaOutput.class.php (55)
…der called at /data/www/wiki.mozilla.org/wiki/extensions/Bugzilla/
Bugzilla.php (163)
in BugzillaRender called at ? (?)
…unc_array called at /data/www/wiki.mozilla.org/wiki/includes/parser/
Parser.php (3744)
…called at /data/www/wiki.mozilla.org/wiki/includes/parser/
Preprocessor_DOM.php (1110)
…M::expand called at /data/www/wiki.mozilla.org/wiki/includes/parser/
Parser.php (2986)
…Variables called at /data/www/wiki.mozilla.org/wiki/includes/parser/
Parser.php (1099)
…rnalParse called at /data/www/wiki.mozilla.org/wiki/includes/parser/
Parser.php (345)
… Parser::parse called at /data/www/wiki.mozilla.org/wiki/includes/
WikiPage.php (2914)
…iew::doWork called at /data/www/wiki.mozilla.org/wiki/includes/
PoolCounter.php (187)
…erWork::execute called at /data/www/wiki.mozilla.org/wiki/includes/
Article.php (587)
…view called at /data/www/wiki.mozilla.org/wiki/includes/actions/
ViewAction.php (40)
in ViewAction::show called at /data/www/wiki.mozilla.org/wiki/includes/Wiki.php (484)
…iki::performAction called at /data/www/wiki.mozilla.org/wiki/includes/
Wiki.php (278)
…ki::performRequest called at /data/www/wiki.mozilla.org/wiki/includes/
Wiki.php (593)
in MediaWiki::main called at /data/www/wiki.mozilla.org/wiki/includes/Wiki.php (503)
in MediaWiki::run called at /data/www/wiki.mozilla.org/wiki/index.php (58)

**Comment by LegNeato** [comment]
This should be fixed, please reopen if it is not!
