### ISSUE TITLE
Use "Zero results found" rather than "No data available in table"

### ISSUE THREAD

**Issue by edmorley** [mozilla/mediawiki-bugzilla#60]
If a bug query returns zero bugs, mediawiki-bugzilla currently displays a single row in the table with text:
"No data available in table"

One of the following would be more helpful (and satisfying to see, when the table is a list of blocker bugs that you've just burnt down!):
"No bugs found"
"Zero results found"
"Zarro results found"

Now I know the term "bug" can be renamed, so we might want to avoid using "bug" if we want to maintain compatibility with non-Mozilla Bugzilla instances.

The string comes from:
https://github.com/mozilla/mediawiki-bugzilla/blob/8fb2cf0180a5183381fd3019d2b90c8564869f0b/web/js/jquery.dataTables.js#L971

http://datatables.net/reference/option/language

**Comment by LegNeato** [comment]
I believe this is fixed by https://github.com/mozilla/mediawiki-bugzilla/pull/82. Please reopen if it is not!
