### ISSUE TITLE
Add more example queries to readme

### ISSUE THREAD

**Issue by edmorley** [mozilla/mediawiki-bugzilla#64]
When creating some of the queries for the Treeherder wiki page, it took a bit of experimentation to get the params correct. This is partly due to having to convert from the API docs, and partly due to the Bugzilla REST API docs being unhelpful.

Either way, let's add some more examples to show how to:
- Exclude multiple bugs from the results, either by direct ID or because they block another bug
- Sort by multiple criteria

eg:
https://wiki.mozilla.org/Auto-tools/Projects/Treeherder#All_others

```
All other open bugs not included above.
<bugzilla>
{
"component": "Treeherder",
"resolution": "---",
"id": "1030636,1059400,1072676,1072681,1054977,1080757", "id_mode": "exclude",
"blocked": "1030636 1059400,1072676,1072681,1054977,1080757", "blocked_type": "not_contains_any_words",
"include_fields": "id, priority, summary, assigned_to",
"order": "priority,assigned_to"
}
</bugzilla>
```

**Comment by mestaritonttu** [comment]
Would appreciate this. I can't figure out how to do "any of".
I've tried:
"blocks": ["102985", "103342", "71732"]
and
"blocks": "102985, 103342, 71732"

But it won't include "any of", just the first one.

**Comment by mestaritonttu** [comment]
> Would appreciate this. I can't figure out how to do "any of".
> I've tried:
> "blocks": ["102985", "103342", "71732"]
> and
> "blocks": "102985, 103342, 71732"
> 
> But it won't include "any of", just the first one.

Dave Miller helped me figure this out today. We can do a custom search and then just pick the fields from the URL produced. Working example:

```
<bugzilla>
    {
        "status": "UNCONFIRMED",
        "f1": "blocked",
        "o1": "anywords",
        "v1": "102985 103342 71732",
        "order": "bug_id"
    }
</bugzilla>
```

A more complex example with "Not" checkbox checked in the first condition, so "Not contains any of the words":

```
<bugzilla>
    {
        "status": ["NEW", "REOPENED", "ASSIGNED"],
        "n1": "1",
        "f1": "keywords",
        "o1": "anywords",
        "v1": "needsDevEval needsUXEval",
        "f2": "keywords",
        "o2": "allwords",
        "v2": "easyHack difficultyBeginner topicQA",
        "order": "bug_id"
    }
</bugzilla>
```

**Comment by cpeterso** [comment]
btw, through trial and error, I documented many of the f/o/v field and operator names here:

https://wiki.mozilla.org/User:Cpeterson
