### ISSUE TITLE
Add support for ordering.

### ISSUE THREAD

**Issue by hwine** [mozilla/mediawiki-bugzilla#67]
I'd like to show "10 most recently fixed bugs" in a wiki page. No matter how I query bugzilla, the result is always returned ordered by id ascending. Thus I can't control the initial display order, and it shows the lowest numbered bugs first.

I can approximate the results by querying for "status changed to resolved in last 2 weeks", but the results are still initially displayed in bug id order - I can't "pre select" "descending date".

**Comment by christi3k** [comment]
Reading the Bugzilla API (http://bugzilla.readthedocs.org/en/latest/api/core/v1/bug.html#search-bugs), it doesn't seem like it supports ordering of results, so this will have to be handled by the extension.

**Comment by globau** [comment]
you can, but it evidently isn't documented :|

use the "order" parameter:  order=<fieldname>[ DESC]

eg. here's the last 10 resolved bugs in the bugzilla.mozilla.org product: https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status&limit=10&order=cf_last_resolved%20desc&product=bugzilla.mozilla.org&resolution=---

**Comment by hwine** [comment]
sweet! Thanks much!
