### ISSUE TITLE
Pagination arrows wrap over two lines, causing excessive whitespace

### ISSUE THREAD

**Issue by edmorley** [mozilla/mediawiki-bugzilla#70]
Sometime in the last 6 months or so the layout for the pagination arrows was broken on wiki.m.o.

The top example is how I would expect it to look, the bottom is how it looks currently:

![arrows](https://cloud.githubusercontent.com/assets/501702/7819546/6443f89a-03da-11e5-9662-45d789b071a4.jpg)

**Comment by SebastianAwatramani** [comment]
Can you give me a link to where this is happening?
