### ISSUE TITLE
Add more committers? 

### ISSUE THREAD

**Issue by LegNeato** [mozilla/mediawiki-bugzilla#75]
It looks like @brandonsavage might not be at Mozilla anymore. Can we get more committers? There looks to be some good pull requests.

I would be happy to be a committer and help maintain again :smile:

**Comment by edmorley** [comment]
I've added you as a committer to the repo. Thank you for offering! :-)

**Comment by brandonsavage** [comment]
I no longer have commit access, or i'd merge some of them. :(

**Comment by LegNeato** [comment]
Thanks! :+1: Now if only I could get my bugzilla docker image sorted so I could test :wink:

**Comment by edmorley** [comment]
@brandonsavage added

**Comment by christi3k** [comment]
I think having a mediawiki instance is more of a blocker than is having a bugzilla instance. How are folks going about making sure PRs will work with current mediawiki and with MozillaWiki? The former is rather straight-forward, the latter is harder, esp for non Mozilla staff.
