### ISSUE TITLE
Switch from BzAPI to the Bugzilla native REST API

### ISSUE THREAD

**Issue by edmorley** [mozilla/mediawiki-bugzilla#83]
Since the former is deprecated and 2-10x slower in many cases. See:
https://bugzilla.mozilla.org/show_bug.cgi?id=1301541
https://bugzilla.mozilla.org/show_bug.cgi?id=1035804

https://github.com/mozilla/mediawiki-bugzilla/blob/a03ebd7c339aa51afe86a2f47eb0a83882de5f6e/Bugzilla.php#L177

**Comment by rdalverny** [comment]
Replacing /bzapi with /rest/ seems to be it?
