### ISSUE TITLE
Set a formal code style

### ISSUE THREAD

**Issue by rdalverny** [mozilla/mediawiki-bugzilla#86]
Using phpcs would help ensure we have a consistent style in the repository, and in PRs as well.

In the current state, I'm not so sure: checking current code style against any of below rulesets returns some significant changes.

 * Is there a phpcs ruleset defined at Mozilla for code? There nearest I found was https://github.com/mozilla-l10n/webstatus/blob/master/.php_cs (I didn't know this - it uses https://github.com/FriendsOfPHP/PHP-CS-Fixer).
 * MediaWiki has [its own set of code style](https://github.com/wikimedia/mediawiki-tools-codesniffer), which could make sense to use here as it's an extension.
 * Or we could use directly PSR1, PSR2 guidelines.

I can set this up in a PR, but choosing the standard is the crux.

**Comment by dennisroczek** [comment]
simply do it - otherwise nothing will happen. :-(

**Comment by LegNeato** [comment]
Fixed in #89.
